fix: Cookie banner with hardcoded mention of edX
openedx/frontend-component-cookie-policy-banner pull request #412
Opened 2022-08-16 07:32 UTC by bezalel001

This PR fixes some hardcoded "edX" reference in the default cookie banner and uses SITE_NAME instead.

2022-08-16 07:33 UTC, openedx-webhooks commented
Thanks for the pull request, @bezalel001!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

<!-- comment:no_cla -->


<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2022-08-16 17:49 UTC, natabene commented
@bezalel001 Thank you for your contribution. Once you fill out the contributor agreement and it has been processed, I will update here and we will be able to review your code.

2022-08-17 06:58 UTC, bezalel001 commented
> @bezalel001 Thank you for your contribution. Once you fill out the contributor agreement and it has been processed, I will update here and we will be able to review your code.

Hi  @natabene 

Done!

2022-08-17 17:08 UTC, natabene commented
Thank you, [bezalel001](https://github.com/bezalel001). Once it has been processed, I will post here, rerun the CLA test and it will go green.

2022-08-30 17:33 UTC, natabene commented
@bezalel001 You are all set with the CLA, the check is green now, thanks for filling out the forms. Could you please look into the failing test now?

2022-08-31 05:29 UTC, bezalel001 commented
> @bezalel001 You are all set with the CLA, the check is green now, thanks for filling out the forms. Could you please look into the failing test now?

@natabene  Fixed!

2022-12-06 14:03 UTC, arbrandes commented
@bezalel001, thanks for the PR!

The problem, though, is that this does not allow one to actually configure what is used in place of "edX" at build time.

2022-12-06 14:03 UTC, arbrandes requested changes
Needs to be revisited.

2022-12-12 13:22 UTC, nedbat commented on src/constants.js
>    [ENGLISH_IETF_TAG]: 'Notice about use of cookies on edx.org.',
I don't know what this is for, but does it need to be generalized away from "edx.org"?

2022-12-12 17:42 UTC, arbrandes commented
@zainab-amir has taken up fixing this issue.  We can close this PR, as there will be another one forthcoming shortly.

2022-12-12 17:43 UTC, closed without merging